Repository CSC207-2022F-UofT/course-project-scrabble, pull requests merged in 2022-12, with the labels that each got.

#154 hot fix for main
  src/main/java/ScrabbleGame/ScrabbleGameController.java
  src/main/java/ScrabbleGame/tile_checker/TileChecker.java
  src/main/java/entities/GameBoard.java
  src/main/java/games_manager/BoardManager.java
  src/main/java/gui/pages/GamePage.java
Labels: bug

#151 added a template for making pull requests
  resources/PullRequestTemplate.md
Labels: documentation

#164 Second hotfix develop
  filename
  resources/gui_resources/actual_scrabble.png
  resources/gui_resources/gui-plan.md
  resources/gui_resources/revised_rules_of_scrabble.md
  resources/gui_resources/rules_of_scrabble.md
  resources/gui_resources/scrabble_board_design.png
  resources/gui_resources/scrabble_board_design.svg
  src/main/game_resources/letters/A.jpg
  src/main/game_resources/letters/B.jpg
  src/main/game_resources/letters/C.jpg
  src/main/game_resources/letters/D.jpg
  src/main/game_resources/letters/E.jpg
  src/main/game_resources/letters/F.jpg
  src/main/game_resources/letters/G.jpg
  src/main/game_resources/letters/H.jpg
  src/main/game_resources/letters/I.jpg
  src/main/game_resources/letters/J.jpg
  src/main/game_resources/letters/K.jpg
  src/main/game_resources/letters/L.jpg
  src/main/game_resources/letters/M.jpg
  src/main/game_resources/letters/N.jpg
  src/main/game_resources/letters/O.jpg
  src/main/game_resources/letters/P.jpg
  src/main/game_resources/letters/Q.jpg
  src/main/game_resources/letters/R.jpg
  src/main/game_resources/letters/S.jpg
  src/main/game_resources/letters/StarDesign.png
  src/main/game_resources/letters/T.jpg
  src/main/game_resources/letters/U.jpg
  src/main/game_resources/letters/V.jpg
  src/main/game_resources/letters/W.jpg
  src/main/game_resources/letters/X.jpg
  src/main/game_resources/letters/Y.jpg
  src/main/game_resources/letters/Z.jpg
  src/main/game_resources/letters/double.png
  src/main/game_resources/letters/letters.md
  src/main/game_resources/letters/tripple.png
  src/main/game_resources/letters/wood.jpg
  src/main/game_resources/revised_rules_of_scrabble.txt
  src/main/java/gui/pages/GamePage.java
  src/main/java/gui/pages/RulesPage.java
Labels: bug

#182 Moved the MoveInfo class from use cases to entities.
  src/main/java/entities/MoveInfo.java
  src/main/java/scrabble_controller/ScrabbleGameController.java
  src/main/java/usecases/usecase_implementations/BoardManager.java
  src/main/java/usecases/usecase_implementations/PlayMove.java
Labels: refactoring

#180 Added new Tests for Happy and Unhappy cases and new Java Docs
  src/main/java/entities/GameBoard.java
  src/main/java/entities/MoveInfo.java
  src/main/java/usecases/usecase_implementations/BoardManager.java
  src/test/java/use_case_implementations/BoardManagerTest.java
Labels: documentation

#179 removed unused print statements in console
  src/main/java/gui/pages/GamePage.java
  src/main/java/usecases/usecase_implementations/BoardManager.java
Labels: refactoring

#188 Added JavaDocs to GameTest
  src/test/java/entities/GameTest.java
Labels: documentation

#194 Fixed bug in BoardManager for Reset Moves use case
  src/main/java/usecases/usecase_implementations/BoardManager.java
  src/main/java/usecases/usecase_interfaces/ResetMoveUsecase.java
Labels: bug
